"""Coordinate asynchronous XPU operator work and batched integration.

This module deliberately does not generate or grade kernels. It creates durable
requests for the xpu-op-gen subagent, freezes a serving baseline, and grades
candidate readiness against that baseline. Candidates are integrated as a
batch: N operators cost one regression run, and a failing batch is attributed
by automated bisection instead of serial one-at-a-time integration.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
# Dispatch deduplication: an operator that already exists in the operator repo
# is a duplicate request, not work. The index is generated by
# tools/build_known_ops_index.py and committed; its absence only disables the
# check, never blocks a dispatch.
DEFAULT_KNOWN_OPS = REPO_ROOT / "catalog" / "known_operators.json"


SUCCESS_STATES = {"DISPATCHED", "DISPATCH_SKIPPED", "BASELINE_FROZEN", "WAITING_FOR_CANDIDATE"}
TERMINAL_INTEGRATION_STATES = {"INTEGRATED_PASS", "INTEGRATED_REGRESSION", "ROLLED_BACK"}


def load_known_operators(path: Path | None) -> set[str]:
    if path is None:
        path = DEFAULT_KNOWN_OPS if DEFAULT_KNOWN_OPS.exists() else None
    if path is None or not path.exists():
        return set()
    payload = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(payload, dict):
        return set(payload.get("operators", []))
    return set(payload)


def _load(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _write(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def _digest(payload: Any) -> str:
    encoded = json.dumps(payload, sort_keys=True, ensure_ascii=False).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def _status(out: Path, state: str, **fields: Any) -> dict[str, Any]:
    payload = {"state": state, **fields}
    _write(out, payload)
    return payload


def dispatch(gaps_path: Path, out_dir: Path, subject: str, baseline_id: str | None = None,
             known_ops: Path | None = None) -> dict:
    """Create one independently executable request per operator gap.

    An operator already present in the known-operators index is skipped and
    recorded as a duplicate, not dispatched: two of GLM-5.2's three dispatches
    were duplicates of kernels XSpeedGate already shipped.
    """
    source = _load(gaps_path)
    gaps = source.get("gaps", source.get("findings", [])) if isinstance(source, dict) else source
    gaps = gaps if isinstance(gaps, list) else []
    known = load_known_operators(known_ops)
    requests = []
    skipped_duplicates = []
    for index, gap in enumerate(gaps, start=1):
        if not isinstance(gap, dict):
            continue
        operator = gap.get("operator") or gap.get("symbol") or gap.get("name")
        if not operator and gap.get("class") == "CAPABILITY_MISSING":
            operator = gap.get("axis")
        if not operator:
            continue
        if operator in known:
            skipped_duplicates.append({
                "operator": operator,
                "reason": "already exists in the operator repo (known-operators index)",
                "index": str(known_ops or DEFAULT_KNOWN_OPS),
            })
            continue
        request = {
            "request_id": f"{subject}-op-{index:03d}",
            "subject": subject,
            "operator": operator,
            "gap": gap,
            "baseline_id": baseline_id,
            "status": "PENDING",
            "required_inputs": [
                "op_contract.json",
                "reference_provenance.json",
                "captured_arguments.jsonl",
                "environment_fingerprint.json",
            ],
        "completion_requires": [
            "generation_manifest.json",
            "build_report.json",
            "kernel_grade.json",
            "dispatch_report.json",
            ],
        }
        requests.append(request)
        _write(out_dir / "requests" / f"{request['request_id']}.json", request)
    state = "DISPATCHED" if requests else "DISPATCH_SKIPPED"
    return _status(
        out_dir / "dispatch_status.json",
        state,
        subject=subject,
        baseline_id=baseline_id,
        request_count=len(requests),
        requests=[request["request_id"] for request in requests],
        skipped_duplicates=skipped_duplicates,
        known_operator_count=len(known),
        source=str(gaps_path),
    )


def freeze_baseline(
    service_path: Path,
    accuracy_path: Path,
    out_dir: Path,
    subject: str,
    environment: dict[str, str],
) -> dict:
    """Freeze the exact evidence that later candidate integrations must preserve."""
    service = _load(service_path)
    accuracy = _load(accuracy_path)
    service_state = service.get("state")
    accuracy_state = accuracy.get("state")
    baseline_id = f"{subject}-baseline-{_digest({'service': service, 'accuracy': accuracy})[:12]}"
    manifest = {
        "baseline_id": baseline_id,
        "subject": subject,
        "service": {"state": service_state, "artifact": str(service_path)},
        "accuracy": {"state": accuracy_state, "artifact": str(accuracy_path)},
        "environment": dict(environment),
        "status": "FROZEN",
        "integration_policy": {
            # One regression run for the whole batch, not one per candidate.
            # Attribution is recovered by automated bisection only when the
            # batch fails, instead of paying N serial regressions up front.
            "one_candidate_at_a_time": False,
            "batch_integration": True,
            "attribution_on_failure": "automated_bisect",
            "require_kernel_pass": True,
            "require_dispatch_confirmation": True,
            "require_service_regression": True,
            "require_accuracy_regression": True,
            "rollback_on_failure": True,
        },
    }
    if service_state != "DEPLOYMENT_READY" or accuracy_state != "ACCURACY_PASS":
        return _status(
            out_dir / "baseline_status.json",
            "BASELINE_REJECTED",
            subject=subject,
            service_state=service_state,
            accuracy_state=accuracy_state,
            reason="service and accuracy must pass before freezing a baseline",
        )
    _write(out_dir / "baseline_manifest.json", manifest)
    return _status(
        out_dir / "baseline_status.json",
        "BASELINE_FROZEN",
        baseline_id=baseline_id,
        manifest=str(out_dir / "baseline_manifest.json"),
    )


READY_GATES = {
    "kernel_grade": "KERNEL_PASS",
    "dispatch_report": "DISPATCH_CONFIRMED",
    "package_swap": "PASS",
    "path_proof": "PASS",
    "service_regression": "PASS",
    "accuracy_regression": "PASS",
}

EVIDENCE_FIELDS = {
    "kernel_grade": "kernel_grade_report",
    "dispatch_report": "dispatch_report_path",
    "package_swap": "package_swap_report",
    "path_proof": "worker_path_log",
    "service_regression": "service_regression_report",
    "accuracy_regression": "accuracy_regression_report",
}


def grade_candidate(candidate: dict) -> dict:
    """Return the failed gates (status mismatches plus missing evidence)."""
    failures = {
        key: candidate.get(key)
        for key, expected in READY_GATES.items()
        if candidate.get(key) != expected
    }
    missing_evidence = {
        status: field for status, field in EVIDENCE_FIELDS.items() if not candidate.get(field)
    }
    failures.update({f"evidence:{key}": value for key, value in missing_evidence.items()})
    return failures


def bisect_plan(candidates: list[dict]) -> list[dict]:
    """Batched bisection schedule attributing a failed batch to one candidate.

    Each round integrates half of the still-suspect candidates and reruns the
    single regression; a failing half is halved again, a passing half exonerates
    its members. ceil(log2(N)) regression runs instead of N.
    """
    suspects = [c.get("candidate_id") or c.get("operator") or str(index)
                for index, c in enumerate(candidates)]
    rounds: list[dict] = []
    round_index = 1
    while len(suspects) > 1:
        midpoint = (len(suspects) + 1) // 2
        probes, carry = suspects[:midpoint], suspects[midpoint:]
        rounds.append({
            "round": round_index,
            "integrate": probes,
            "exonerated_if_pass": carry,
        })
        # The executor keeps whichever half fails; the plan shows both halves so
        # either outcome has an unambiguous next action.
        suspects = probes if len(probes) > 1 else carry or probes
        round_index += 1
    rounds.append({"round": round_index, "integrate": suspects, "exonerated_if_pass": []})
    return rounds


def integration_decision(
    baseline_path: Path,
    candidate_paths: list[Path],
    out_dir: Path,
    subject: str,
) -> dict:
    """Grade a batch of candidates; actual service mutation remains an explicit step."""
    baseline = _load(baseline_path)
    if not candidate_paths:
        return _status(
            out_dir / "integration_status.json",
            "WAITING_FOR_CANDIDATE",
            subject=subject,
            baseline_id=baseline.get("baseline_id"),
            next_action="provide candidate manifests (repeat --candidate per operator)",
        )
    graded = []
    rejected = {}
    for candidate_path in candidate_paths:
        candidate = _load(candidate_path)
        candidate_id = candidate.get("candidate_id") or candidate.get("operator") or candidate_path.stem
        failures = grade_candidate(candidate)
        graded.append({"candidate_id": candidate_id, "candidate": str(candidate_path),
                       "failed_gates": failures})
        if failures:
            rejected[candidate_id] = failures
    if rejected:
        return _status(
            out_dir / "integration_status.json",
            "CANDIDATE_REJECTED",
            subject=subject,
            baseline_id=baseline.get("baseline_id"),
            candidates=graded,
            failed_candidates=sorted(rejected),
            next_action="drop or rework the rejected candidates; the rest of the batch "
                        "is still eligible",
        )
    return _status(
        out_dir / "integration_status.json",
        "READY_FOR_INTEGRATION",
        subject=subject,
        baseline_id=baseline.get("baseline_id"),
        candidates=graded,
        batch_size=len(graded),
        next_action="integrate the whole batch and run one regression; on failure run "
                    "the recorded bisect schedule",
        bisect_schedule=bisect_plan([_load(p) for p in candidate_paths]),
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="action", required=True)

    dispatch_parser = sub.add_parser("dispatch")
    dispatch_parser.add_argument("--gaps", type=Path, required=True)
    dispatch_parser.add_argument("--out", type=Path, required=True)
    dispatch_parser.add_argument("--subject", required=True)
    dispatch_parser.add_argument("--baseline-id")
    dispatch_parser.add_argument("--known-ops", type=Path,
                                 help="known-operators index; defaults to "
                                      "catalog/known_operators.json when present")

    baseline_parser = sub.add_parser("freeze-baseline")
    baseline_parser.add_argument("--service", type=Path, required=True)
    baseline_parser.add_argument("--accuracy", type=Path, required=True)
    baseline_parser.add_argument("--out", type=Path, required=True)
    baseline_parser.add_argument("--subject", required=True)
    baseline_parser.add_argument("--env", action="append", default=[])

    integration_parser = sub.add_parser("integrate")
    integration_parser.add_argument("--baseline", type=Path, required=True)
    integration_parser.add_argument("--candidate", type=Path, action="append", default=[],
                                    help="candidate manifest; repeat once per operator")
    integration_parser.add_argument("--out", type=Path, required=True)
    integration_parser.add_argument("--subject", required=True)
    args = parser.parse_args()

    if args.action == "dispatch":
        dispatch(args.gaps, args.out, args.subject, args.baseline_id, args.known_ops)
    elif args.action == "freeze-baseline":
        environment = dict(pair.split("=", 1) for pair in args.env)
        freeze_baseline(args.service, args.accuracy, args.out, args.subject, environment)
    else:
        integration_decision(
            args.baseline,
            [Path(candidate) for candidate in args.candidate],
            args.out,
            args.subject,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
